cmake_minimum_required(VERSION 3.10)
if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
    if(DEFINED ENV{VITASDK})
        set(CMAKE_TOOLCHAIN_FILE "$ENV{VITASDK}/share/vita.toolchain.cmake" CACHE PATH "toolchain file")
    else()
        message(FATAL_ERROR "Please define VITASDK")
    endif()
endif()
project(vbe_iftu_csc_trace C)
include("${VITASDK}/share/vita.cmake" REQUIRED)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wl,-q -Wall -Wextra -Werror -O2 -fno-pic -fno-PIC -std=gnu99")
add_executable(vbe_iftu_csc_trace main.c)
target_link_libraries(vbe_iftu_csc_trace taihenForKernel_stub SceIofilemgrForDriver_stub SceSysclibForDriver_stub gcc)
set_target_properties(vbe_iftu_csc_trace PROPERTIES LINK_FLAGS "-nostdlib" COMPILE_FLAGS "-D__VITA_KERNEL__")
vita_create_self(vbe_iftu_csc_trace.skprx vbe_iftu_csc_trace CONFIG ${CMAKE_CURRENT_SOURCE_DIR}/module.yml UNSAFE)
