#!/usr/bin/env python3
"""Generate the Q16.16 CCT anchor table used by affine_core.c.

The approximation is deliberately code-space only.  It uses the common Tanner
Helland RGB-temperature approximation, normalizes each channel against that
approximation's 6500 K RGB value, rounds to Q16.16, and forces 6500 K to exact
identity.  This is not linear-light chromatic adaptation and must not be
presented as such.
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path

ANCHORS = (
    1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 5500, 6000,
    6500, 7000, 8000, 9000, 10000, 12000, 15000, 18000, 22000, 25100,
)
Q16 = 65536


def clamp8(value: float) -> float:
    return max(0.0, min(255.0, value))


def helland_rgb(kelvin: int) -> tuple[float, float, float]:
    t = kelvin / 100.0
    if t <= 66.0:
        r = 255.0
        g = 99.4708025861 * math.log(t) - 161.1195681661
        b = 0.0 if t <= 19.0 else 138.5177312231 * math.log(t - 10.0) - 305.0447927307
    else:
        r = 329.698727446 * ((t - 60.0) ** -0.1332047592)
        g = 288.1221695283 * ((t - 60.0) ** -0.0755148492)
        b = 255.0
    return clamp8(r), clamp8(g), clamp8(b)


def q16_gain(value: float, reference: float) -> int:
    return int(round((value / reference) * Q16))


def render() -> str:
    reference = helland_rgb(6500)
    rows = []
    for kelvin in ANCHORS:
        if kelvin == 6500:
            gains = (Q16, Q16, Q16)
        else:
            rgb = helland_rgb(kelvin)
            gains = tuple(q16_gain(rgb[i], reference[i]) for i in range(3))
        rows.append("    { %5d, %5d, %5d, %5d }," % (kelvin, *gains))
    return """/* Generated by tools/generate_cct_table.py. Do not edit manually. */
#pragma once

static const CctAnchor k_cct[] = {
%s
};
""" % "\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="generated/cct_anchors.h")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = Path(args.output)
    content = render()
    if args.check:
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            raise SystemExit(f"generated CCT table differs: {path}")
        print("CCT provenance regressions: OK")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
